name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag prateek2408/juno
    - shell: bash
      env:
        REPO_SECRET: ${{ secrets.DOCKER_REPO_PASS }} 
        name: Push the image
        run: docker login -u prateek2408 -p $REPO_SECRET; docker push prateek2408/juno
