‐ name: build
  id: build
  uses: docker/build-action@v1
  with:
    repository: myorg/myrepo
    tags: v1
‐ name: login
  uses: docker/login-action@v1
  with:
    registry: myregistry
    username: ${{ DOCKER_USERNAME }}
    password: ${{ DOCKER_PASSWORD }}
‐ name: push
  uses: docker/push-action@v1
  with:
    registry: myregistry
    tags: ${{ outputs.build.tags }}
